name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install backend deps
        working-directory: backend
        run: |
          npm ci

      - name: Run backend lint (if any)
        working-directory: backend
        run: |
          echo "No backend lint configured"

      - name: Install frontend deps
        working-directory: frontend
        run: |
          npm ci

      - name: Build frontend
        working-directory: frontend
        run: |
          npm run build

      - name: Run frontend tests (if any)
        working-directory: frontend
        run: |
          echo "No frontend tests configured"